sdk.development.store_uncommitted_code_diff: false

api { 
    web_server: https://clearml-hrl-03.haifa.ibm.com:8080
    api_server: https://clearml-hrl-03.haifa.ibm.com:8008
    files_server: https://clearml-hrl-03.haifa.ibm.com:8081
    credentials {
        "access_key" = "79QU24LJ9MSXTWDEL82F"
        "secret_key"  = "rZ72BEQY3NeyKxuHPa0su3lsbfVZpAbF2LocTYI9uN89qyEUG0"
    }
}

