__merge__: /src/api/comp_method.yaml
name: "biomed_rna"
label: BIOMED_RNA
summary: "BIOMED-RNA is a large transformer model trained on large scRNA data that enalbles fine tuninign an predictions of varioud scRNA related tasks."
description: |
  TBD
references:
  doi:
    - 10.48550/arXiv.2506.14861
links:
  repository: https://github.com/BiomedSciAI/biomed-multi-omic
  documentation: https://github.com/BiomedSciAI/biomed-multi-omic


# description: |
#   single-cell ANnotation using Variational Inference is a
#   semi-supervised variant of the scVI(Lopez et al. 2018) algorithm. Like scVI,
#   scANVI uses deep neural networks and stochastic optimization to model
#   uncertainty caused by technical noise and bias in single - cell
#   transcriptomics measurements. However, scANVI also leverages cell type labels
#   in the generative modelling. In this approach, scANVI is used to predict the
#   cell type labels of the unlabelled test data.

# info:
#   v1:
#     path: openproblems/tasks/label_projection/methods/scvi_tools.py
#     commit: e3be930c6d4bbd656ab1e656badb52bb50e6cdd6
#   preferred_normalization: counts
#   variants:
#     scanvi_all_genes:
#     scanvi_hvg:
# #       num_hvg: 2000
# arguments:
#   - name: "--num_hvg"
#     type: integer
#     description: "The number of HVG genes to subset to."

# requirements:
#     memory: 512GB     
#     cpus: 32

resources:
  - type: python_script
    path: script.py
  - type: file
    path: clearml.conf
    dest: clearml.conf
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: python
      - type: docker
        run: |
          cd /opt && git clone https://github.com/BiomedSciAI/biomed-multi-omic.git && pip install /opt/biomed-multi-omic
  
runners:
  - type: executable    
    docker_run_args: >
      --gpus 1 
      --shm-size=128g
      --stop-timeout 120  # Gives it 2 minutes to shut down instead of 10s
    # -u ${HOST_UID}:${HOST_GID}
    # -e HOME=/tmp/home
    # -e PYTHONUNBUFFERED=1
    # -e HDF5_USE_FILE_LOCKING=FALSE
    # -e CUDA_VISIBLE_DEVICES=0
    #  -e MPLCONFIGDIR=/tmp/matplotlib
    # -e NUMBA_CACHE_DIR=/tmp/numba_cache
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu, gpu]
      #containerOptions: "--gpus all"
      # containerOptions: >
      #   --gpus 1
      #   -u ${HOST_UID}:${HOST_GID}
      #   -e PYTHONUNBUFFERED=1
      #   -e HDF5_USE_FILE_LOCKING=FALSE
      #   -e CUDA_VISIBLE_DEVICES=0