__merge__: /src/api/comp_method.yaml
name: "biomed_rna"
label: BIOMED_RNA
# summary: "scANVI predicts cell type labels for unlabelled test data by leveraging cell type labels, modelling uncertainty and using deep neural networks with stochastic optimization."
# description: |
#   single-cell ANnotation using Variational Inference is a
#   semi-supervised variant of the scVI(Lopez et al. 2018) algorithm. Like scVI,
#   scANVI uses deep neural networks and stochastic optimization to model
#   uncertainty caused by technical noise and bias in single - cell
#   transcriptomics measurements. However, scANVI also leverages cell type labels
#   in the generative modelling. In this approach, scANVI is used to predict the
#   cell type labels of the unlabelled test data.
# references:
#   doi:
#     - 10.1101/2020.07.16.205997
# links:
#   repository: https://github.com/scverse/scvi-tools
#   documentation: https://scarches.readthedocs.io/en/latest/scanvi_surgery_pipeline.html
# info:
#   v1:
#     path: openproblems/tasks/label_projection/methods/scvi_tools.py
#     commit: e3be930c6d4bbd656ab1e656badb52bb50e6cdd6
#   preferred_normalization: counts
#   variants:
#     scanvi_all_genes:
#     scanvi_hvg:
# #       num_hvg: 2000
# arguments:
#   - name: "--num_hvg"
#     type: integer
#     description: "The number of HVG genes to subset to."

resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    #image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
    #image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-python3.11
    #image: pytorch/pytorch:2.0.1-cuda11.8-cudnn8-python3.10
    #image: pytorch/pytorch:2.x-cuda11.8-python3.10
    #image: pytorch/pytorch:1.10.2-cuda11.2-cudnn8-python3.9
    setup:
      # - type: apt
      #   packages:
      #     - procps
      #     - git
      - type: python
        #   - git+https://${GITHUB_TOKEN}@github.com/BiomedSciAI/biomed-multi-omic.git
      - type: docker
        run: |
          cd /opt && git clone --branch train_and_predict https://github.com/BiomedSciAI/biomed-multi-omic.git && pip install /opt/biomed-multi-omic
          
        #2 cd /opt && git clone https://github.com/BiomedSciAI/biomed-multi-omic.git && pip install /opt/biomed-multi-omic && pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

        
        #pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
        #pip install -U "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

        #pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
        #pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html


        # cd /opt && git clone https://@github.com/BiomedSciAI/biomed-multi-omic.git
        # cd biomed-multi-omic && pip install .
        # echo "export BIOMED_ROOT=/opt/biomed-multi-omic" >> /etc/profile
        
        #"git clone https://${GITHUB_TOKEN}@github.com/BiomedSciAI/biomed-multi-omic.git"

        # chat suggest this for mac
          # if [ "$(uname -s)" = "Linux" ]; then
          #   pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
          # else
          #   pip install -U jax jaxlib
          # fi
    

runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu, gpu]
      containerOptions: "--gpus all -v $HOME/clearml.conf:/root/clearml.conf:ro"
