__merge__: /src/api/comp_score.yaml
name: "print_score"
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        packages: scikit-learn
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
